#include <math.h>
#include <stdio.h>
#include "fixedpointmath.h"

fp8p24_t ln_base_fx_table[0x3fff];
fp8p24_t ln_step_fx_table[0x3fff];

int main(int argc, char **argv) {
	int l, l_max;

	l_max = 0x3fff;

	double ln_base, ln_step;

	
	for(l = 0; l < l_max; l++) {		

		if(l == 0) {
			ln_base = log(1.0 / 16777216.0);
		} else {
			ln_base = log(fp8p24tod(l << 10));
		}
		ln_step = log(fp8p24tod((l + 1) << 10));
		ln_step = (ln_step - ln_base) / ((double) 0x3ff);
		
		fp8p24_t ln_base_fx, ln_step_fx;

		ln_base_fx = dtofp8p24(ln_base);
		ln_step_fx = dtofp8p24(ln_step);

		ln_base_fx_table[l] = ln_base_fx;
		ln_step_fx_table[l] = ln_step_fx;		
	}

	printf("/* Autogenerated look-up-table for natural logarithm, log(x), for 0.0 < x < 1.0 */\n\n");
	printf("#include <stdint.h>\n\n");
	printf("#define HAS_AUTOGEN_NAT_LOG_LUT\n\n");
	printf("#define small_ln_fp8p24(x) (ln_base_fx_table[(x & 0x00fffc00) >> 10] + mulfp8p24((x & 0x3ff), ln_step_fx_table[(x & 0x00fffc00) >> 10]))\n\n");

	printf("uint32_t ln_base_fx_table[] = {\n");
	for(l = 0; l < l_max; l++) {
		if(l > 0)
			printf(",\n");
		printf("0x%08lx", (uint32_t)ln_base_fx_table[l]);
	}
	printf("\n};\n\n");

	printf("uint32_t ln_step_fx_table[] = {\n");
	for(l = 0; l < l_max; l++) {
		if(l > 0)
			printf(",\n");
		printf("0x%08lx", (uint32_t)ln_step_fx_table[l]);
	}
	printf("\n};\n\n");
	
}
